124 metrics init
dreamit-de/graphql-server pull request #125
Opened 2023-02-06 17:05 UTC by sgohlke

Fixes issues in #124 
Note:
In the next major release we should think about using a non prom-client MetricsClient as default. The usage of the global object in prom-client tends to create unexpected behaviour and is not a good choice for multiple GraphQLServer instances.
Closes #124

2023-02-06 19:56 UTC, jenssuhr approved these changes

2023-02-06 22:07 UTC, swunderlich commented on tests/server/GraphQLServer.test.ts
> +    console.info('Running new test')
Please remove

2023-02-06 22:20 UTC, swunderlich commented on src/server/GraphQLServer.ts
> +        this.options.metricsClient.setAvailability(this.isValidSchema(this.options.schema) ? 1 : 0)
```suggestion
       const { cpuUsage } = process
       this.options.metricsClient = metricsClient || (typeof cpuUsage === 'function') ?
           new DefaultMetricsClient() : new SimpleMetricsClient()
        this.options.metricsClient.setAvailability(this.isValidSchema(this.options.schema) ? 1 : 0)
```

2023-02-06 22:22 UTC, swunderlich requested changes
See comments

2023-02-07 07:10 UTC, pro-ship-it reviewed
Looks good to me

2023-02-07 07:11 UTC, pro-ship-it approved these changes

2023-02-07 12:44 UTC, merged